"""Read-only match page: events, stats, lineups, prediction, odds, H2H."""

from __future__ import annotations

from predictor.services.match_detail.domain import (
    ATTACK_SUB_WINDOW,
    AttackChange,
    DetailEvent,
    DetailH2H,
    DetailPlayer,
    DetailStat,
    GoalPrice,
    GroupTable,
    MatchDetail,
    OddsMarket,
    OddsQuote,
    RankedSlot,
    SplitPreview,
    StandingSlot,
    _none_odd,
    _over_odd,
    _snapshot_includes_match,
    apply_score,
    build_group_table,
    point_splits,
    points_split,
    rank_slots,
    read_goal_price,
    recent_attack_changes,
    select_display_markets,
)
from predictor.services.match_detail.html import (
    render_match_html,
    render_match_missing,
)
from predictor.services.match_detail.sql import (
    _goal_price,
    _lineup_strength,
    _live_markets,
    load_match_detail,
)

__all__ = [
    "ATTACK_SUB_WINDOW",
    "AttackChange",
    "GoalPrice",
    "DetailEvent",
    "DetailStat",
    "DetailPlayer",
    "DetailH2H",
    "StandingSlot",
    "RankedSlot",
    "SplitPreview",
    "GroupTable",
    "MatchDetail",
    "OddsQuote",
    "OddsMarket",
    "load_match_detail",
    "points_split",
    "rank_slots",
    "apply_score",
    "point_splits",
    "build_group_table",
    "_snapshot_includes_match",
    "recent_attack_changes",
    "select_display_markets",
    "read_goal_price",
    "_goal_price",
    "_lineup_strength",
    "_live_markets",
    "_none_odd",
    "_over_odd",
    "render_match_missing",
    "render_match_html",
]
